packages:
  - "packages/dashboard"
  - "packages/ledger"
  - "packages/listing"
  - "packages/shared"

allowBuilds:
  esbuild: set this to true or false
  msw: set this to true or false
  unrs-resolver: set this to true or false

onlyBuiltDependencies:
  - esbuild
  - msw
  - unrs-resolver
